version: "3"
services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: front-end-image:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: back-end-image:latest
    ports:
      - "5000:5000"
